---
name: presentation-corkscrew-magnetism-mnau2
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.4.4
  - black=19.3b0
  - flake8=3.7.7
  - ipython=7.5.0
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.24.2
  - pandoc=2.7.3
  - pip=19.1.1
  - pre_commit=1.17.0
  - pydocstyle=3.0.0
  - python=3.7.3
  - pytoml=0.1.20
  - r-base=3.5.1
  - r-essentials=3.5.1
  - r-reticulate=1.12
  - rpy2=2.9.4
  - scipy=1.3.0
  - pip:
    - entrypoints==0.3
    - flake8-bugbear==19.3.0
    - ghp-import==0.5.5
    - grip==4.5.2
    - mypy==0.701
    - seed-isort-config==1.9.1
